# GitBridge Webhook System Configuration
# Version: 2.1.0
# Environment: development

# Server settings
server:
  host: "0.0.0.0"
  port: 8000
  debug: true
  ssl_enabled: false

# Security settings
security:
  webhook_secret: "${GITHUB_WEBHOOK_SECRET}"
  allowed_ips:
    - "192.30.252.0/22"  # GitHub webhooks
    - "185.199.108.0/22" # GitHub API
  signature_header: "X-Hub-Signature-256"
  max_payload_size: 10485760  # 10MB

# Queue settings
queue:
  type: "redis"  # or "asyncio" for backward compatibility
  redis_url: "redis://localhost:6379/0"
  max_size: 10000
  timeout: 30
  retry_policy:
    max_retries: 3
    base_delay: 1  # seconds

# Task chain settings
task_chain:
  states:
    - Created
    - Queued
    - ConsensusPending
    - Resolved
    - Failed
  max_concurrent: 10
  consensus_required: true

# Rate limiting
rate_limit:
  enabled: true
  redis_url: "redis://localhost:6379/0"
  default_limit: 100  # requests per hour
  burst_limit: 10    # requests per minute

# Monitoring
monitoring:
  prometheus_port: 9090
  metrics:
    - queue_depth
    - event_processing_time
    - task_state_transitions
    - error_rates
  grafana:
    dashboard_uid: "webhook-system"
    refresh_interval: 10

# Logging
logging:
  level: "INFO"
  format: "json"
  files:
    event_log: "logs/event_log.json"
    mas_log: "logs/mas_log.json"
    error_log: "logs/error_log.json"

# Development tools
dev_tools:
  mock_github_api: true
  test_webhook_endpoint: "/test-webhook"
  openapi:
    enabled: true
    output_formats:
      - markdown
      - html
      - pdf

# Environment-specific overrides
environments:
  development:
    server:
      debug: true
    security:
      allowed_ips:
        - "127.0.0.1"
    logging:
      level: "DEBUG"

  staging:
    server:
      debug: false
    security:
      allowed_ips:
        - "192.30.252.0/22"
    logging:
      level: "INFO"

  production:
    server:
      debug: false
      ssl_enabled: true
    security:
      allowed_ips:
        - "192.30.252.0/22"
    logging:
      level: "WARNING"
    monitoring:
      grafana:
        refresh_interval: 30 