name: Commit Validation

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  actions: write
  checks: write
  pull-requests: write
  statuses: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITBRIDGE_TOKEN }}

    - name: Set up Python 3.13.3
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint flake8 pytest pytest-asyncio pytest-cov tox

    - name: Validate Commit
      env:
        GITBRIDGE_TOKEN: ${{ secrets.GITBRIDGE_TOKEN }}
      run: |
        pylint --max-line-length=88 scripts/ mas_core/ tests/
        flake8 --max-line-length=88 scripts/ mas_core/ tests/
        yamllint -c .yamllint.yml .

    - name: Run tests
      env:
        GITBRIDGE_TOKEN: ${{ secrets.GITBRIDGE_TOKEN }}
      run: |
        export PYTHONPATH=$(pwd)
        tox -e py3

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        token: ${{ secrets.GITBRIDGE_TOKEN }} 