name: Commit Validation

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.3]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITBRIDGE_TOKEN }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint flake8 pytest pytest-asyncio pytest-cov tox

    - name: Validate commit messages
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: .commitlintrc.json
        token: ${{ secrets.GITBRIDGE_TOKEN }}

    - name: Run Pylint
      run: |
        pylint --max-line-length=88 scripts/ mas_core/ tests/

    - name: Run Flake8
      run: |
        flake8 --max-line-length=88 scripts/ mas_core/ tests/

    - name: Validate YAML files
      run: |
        pip install yamllint
        yamllint -c .yamllint.yml .

    - name: Run tests
      run: |
        export PYTHONPATH=$(pwd)
        tox -e py313

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        token: ${{ secrets.GITBRIDGE_TOKEN }} 