name: Commit Validation

on:
  push:
    branches: [ main, feature/*, hotfix/* ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
      checks: write
      pull-requests: write
      statuses: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-webhook.txt
          
      - name: Validate Commit
        env:
          GITBRIDGE_TOKEN: ${{ secrets.GITBRIDGE_TOKEN }}
        run: |
          chmod +x scripts/validate_commit.sh
          ./scripts/validate_commit.sh
          
      - name: Run Tests
        run: |
          pip install pytest pytest-cov
          pytest tests/ -v --cov=./ --cov-report=xml
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true 